src/Entity/User.php
<?php
//src/Entity/User.php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use FOS\UserBundle\Model\User as BaseUser;
use Doctrine\ORM\Mapping as ORM;

use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass="App\Repository\UserRepository")
 * @ORM\Table(name="um_user")
 */
class User extends BaseUser
{
    /**
     * @ORM\Id
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Group", mappedBy="users", cascade={"persist"})
     */
    private $user_groups;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     * @Assert\NotBlank()
     */
    private $name;

    public function __construct()
    {
        parent::__construct();
        $this->user_groups = new ArrayCollection();
    }

    /**
     * @return Collection|Group[]
     */
    public function getUserGroups(): Collection
    {
        return $this->user_groups;
    }

    public function addUserGroup(Group $userGroup): self
    {
        if (!$this->user_groups->contains($userGroup)) {
            $this->user_groups[] = $userGroup;
            $userGroup->addUser($this);
        }

        return $this;
    }

    public function removeUserGroup(Group $userGroup): self
    {
        if ($this->user_groups->contains($userGroup)) {
            $this->user_groups->removeElement($userGroup);
            $userGroup->removeUser($this);
        }

        return $this;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(?string $name): self
    {
        $this->name = $name;

        return $this;
    }
}

src/Form/UserType.php
<?php
/**
 * Created by PhpStorm.
 * User: madhav
 * Date: 2019-03-07
 * Time: 21:27
 */

namespace App\Form;

use App\Entity\User;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\CollectionType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\OptionsResolver\OptionsResolver;


class UserType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('name')
            ->add('username')
            ->add('email')
            ->add('plain_password')
            ->add('roles', ChoiceType::class, [
                    'choices' => [
                        'USER' => 'ROLE_USER',
                        'ADMIN' => 'ROLE_ADMIN'
                    ],
                    'multiple' => true
                ])
            ->add('user_groups')
            ->add('save', SubmitType::class, ['label' => 'Save changes'])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => User::class,
        ]);
    }
}

src/Controller/UserController.php
<?php

namespace App\Controller;

use App\Entity\Group;
use App\Entity\User;
use App\Form\UserType;
use App\Services\GroupService;
use App\Services\UserService;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\Request;

class UserController extends AbstractController
{
    /**
     * @Route("/admin/user", name="user")
     */
    public function index()
    {
        return $this->redirectToRoute('admin');
    }

    /**
     * @Route("/admin/user/add", name="addUser")
     */
    public function addUser(Request $request, UserService $userService, GroupService $groupService)
    {
        $user = new User();
        return $this->handleForm($request, $userService, $groupService, $user);
    }
    /**
     * @Route("/admin/user/edit", name="editUser")
     */
    public function editUser(Request $request, UserService $userService, GroupService $groupService)
    {
        $id = $request->get('id', null);
        if($id) {
            $user = $userService->findUserById($id);
            return $this->handleForm($request, $userService, $groupService, $user);
        } else {
            return $this->redirectToRoute('admin');
        }
    }
    /**
     * @Route("/admin/user/delete", name="deleteUser")
     */
    public function deleteUser(Request $request, UserService $userService)
    {
        $id = $request->get('id', null);
        if($id) {
            $user = $userService->findUserById($id);
            $userService->delete($user);
        }
        return $this->redirectToRoute('admin');
    }
    private function handleForm(Request $request, UserService $userService, GroupService $groupService, User $user) {
        $form = $this->createForm(UserType::class, $user);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $user = $form->getData();
            // Clean up groups first
            /* @var $group Group */
            foreach ($groupService->findAll() as $group) {
                $group->removeUser($user);
                $groupService->update($group);
            }
            // Now add the user to the group if necessary
            /* @var $userGroup Group */
            foreach ($user->getUserGroups() as $userGroup) {
                $userGroup->addUser($user);
                $groupService->update($userGroup);
            }
            if($userService->findUser($user)) {
                $userService->update($user);
            } else {
                $userService->create($user);
            }
            return $this->redirectToRoute('admin');
        }
        return $this->render('user/form.html.twig', [
            'form' => $form->createView(),
        ]);
    }
}

templates/user/form.html.twig
{% extends 'base.html.twig' %}

{% block title %}User Management Demo{% endblock %}

{% block body %}
    <div class="center-wrapper">
        <div class="content">
            <section class="content-header ">
                <div class="d-flex flex-row justify-content-between align-content-center w-100">
                    <div class="content-header-title">
                        <h1 class="title">Manage User</h1>
                    </div>
                </div>
            </section>

            <section id="main" class="content-body">


                {{ form_start(form) }}
                <div class="my-custom-class-for-errors">
                    {{ form_errors(form) }}
                </div>

                <div class="row">
                    <div class="col-12 ">
                        <div class="form-group  field-text">
                            {{ form_label(form.name) }}
                            <div class="form-widget">
                                {{ form_widget(form.name, {'attr': {'class': 'form-control'}}) }}
                            </div>
                            <small>{{ form_help(form.name) }}</small>
                            <div class="form-error">
                                {{ form_errors(form.name) }}
                            </div>
                        </div>
                    </div>
                    <div class="col-12 ">
                        <div class="form-group  field-text">
                            {{ form_label(form.username) }}
                            <div class="form-widget">
                                {{ form_widget(form.username, {'attr': {'class': 'form-control'}}) }}
                            </div>
                            <small>{{ form_help(form.username) }}</small>
                            <div class="form-error">
                                {{ form_errors(form.username) }}
                            </div>
                        </div>
                    </div>
                    <div class="col-12 ">
                        <div class="form-group  field-text">
                            {{ form_label(form.email) }}
                            <div class="form-widget">
                                {{ form_widget(form.email, {'attr': {'class': 'form-control'}}) }}
                            </div>
                            <small>{{ form_help(form.email) }}</small>
                            <div class="form-error">
                                {{ form_errors(form.email) }}
                            </div>
                        </div>
                    </div>
                    <div class="col-12 ">
                        <div class="form-group  field-text">
                            {{ form_label(form.plain_password) }}
                            <div class="form-widget">
                                {{ form_widget(form.plain_password, {'attr': {'class': 'form-control'}}) }}
                            </div>
                            <small>{{ form_help(form.plain_password) }}</small>
                            <div class="form-error">
                                {{ form_errors(form.plain_password) }}
                            </div>
                        </div>
                    </div>
                    <div class="col-12 ">
                        <div class="form-group  field-text">
                            {{ form_label(form.roles) }}
                            <div class="form-widget">
                                {{ form_widget(form.roles, {'attr': {'class': 'form-control'}}) }}
                            </div>
                            <small>{{ form_help(form.roles) }}</small>
                            <div class="form-error">
                                {{ form_errors(form.roles) }}
                            </div>
                        </div>
                    </div>
                    <div class="col-12 ">
                        <div class="form-group  field-text">
                            {{ form_label(form.user_groups) }}
                            <div class="form-widget">
                                {{ form_widget(form.user_groups, {'attr': {'class': 'form-control'}}) }}
                            </div>
                            <small>{{ form_help(form.user_groups) }}</small>
                            <div class="form-error">
                                {{ form_errors(form.user_groups) }}
                            </div>
                        </div>
                    </div>
                </div>
            </section>
            <section class="content-footer">
                <div class="form-actions">
                    {{ form_widget(form.save, {'attr': {'class': 'btn btn-primary action-save'}}) }}
                    <a class="btn btn-link pr-0 action-list" title="" href="{{ path('admin') }}" target="_self">Back to listing</a>
                </div>
            </section>
            {{ form_end(form) }}

        </div>
    </div>
{% endblock %}

templates/user/list.html.twig
<h2>Manage Users <a class="btn btn-primary action-new" href="{{ path('addUser') }}">Add User</a></h2>
<br />
<table class="table datagrid">
    <thead>
    <tr>
        <th><span>Name</span></th>
        <th><span>Username</span></th>
        <th><span>Email</span></th>
        <th><span>Groups</span></th>
        <th><span>Roles</span></th>
        <th>
            <span></span>
        </th>
    </tr>
    </thead>

    <tbody>
    {% for item in list %}
        <tr>
            <td>{{ item.name }}</td>
            <td>{{ item.username }}</td>
            <td>{{ item.email }}</td>
            <td>{{ item.userGroups |join(', ', ' and ') }}</td>
            <td>{{ item.roles |join(', ', ' and ') }}</td>
            <td class="actions">
                <a class="action-edit" href="{{ path('editUser', {'id': item.id}) }}">Edit</a>
                <a class="text-danger action-delete" href="{{ path('deleteUser', {'id': item.id}) }}"  onclick="confirm('Are you sure to delete this item?') || event.preventDefault()">Delete</a>
            </td>
        </tr>
    {% else %}
        <tr>
            <td class="no-results" colspan="5">
                Sorry no records found.
            </td>
        </tr>
    {% endfor %}
    </tbody>
</table>